

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import NavBar from './components/NavBar'

import { SessionProvider } from "next-auth/react"
import { auth } from "../../auth"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Art Tracker Website',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  if (session?.user) {
    // @ts-expect-error TODO: Look into https://react.dev/reference/react/experimental_taintObjectReference
    // filter out sensitive data before passing to client.
    session.user = {
      name: session.user.name,
      email: session.user.email,
      image: session.user.image,
    }
  }
  return (
    <SessionProvider session={session}>
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <div className='w-full max-w-7xl mt-4 m-auto'>
            {children}
        </div>
      </body>
    </html>
    </SessionProvider>
  )
}